// ---------- Wrapped ("Retrospectiva") ----------
//
// A Wrapped edition is a Spotify-Wrapped-style recap generated once per room
// per edition and cached in D1. Stats are computed with SQL over `requests`;
// the narrative layer (persona, captions, dynamic highlights) is generated by
// the LLM from those stats plus a sample of real donor messages.
//
// `private` carries money stats (R$ totals, top donors by amount). It is only
// returned to the authenticated room owner — the public endpoint strips it.

// The whole retrospective — narrative AND UI labels — renders in one language,
// picked by the streamer at generation time and baked into the payload.
export type WrappedLanguage = 'pt-BR' | 'en';

export interface WrappedRankEntry {
  character: string;
  count: number;
}

export interface WrappedRequesterEntry {
  donor: string;
  count: number;
}

export interface WrappedStats {
  totalRequests: number;
  doneRequests: number;
  killerCount: number;
  survivorCount: number;
  distinctCharacters: number;
  distinctRequesters: number;
  topKillers: WrappedRankEntry[];
  topSurvivors: WrappedRankEntry[];
  topRequesters: WrappedRequesterEntry[];
  monthly: { month: string; count: number }[]; // 'YYYY-MM', ascending
  busiestDay: { date: string; count: number } | null; // 'YYYY-MM-DD'
  sources: { donation: number; resub: number; chat: number; manual: number };
  firstRequest: { donor: string; character: string; timestamp: string } | null;
  loyalFan: { donor: string; character: string; count: number } | null;
}

export interface WrappedPrivate {
  totalAmount: number;
  donationCount: number;
  topDonors: { donor: string; total: number }[];
  biggestDonation: { donor: string; amount: number; character: string } | null;
}

export interface WrappedHighlight {
  title: string;
  text: string;
  // Official character name when the highlight is about a specific character
  // (lets the UI show their portrait instead of a generic mark).
  character?: string;
}

export interface WrappedNarrative {
  personaTitle: string;
  personaText: string;
  intro: string;
  captions: {
    totals?: string;
    topKiller?: string;
    topSurvivor?: string;
    ratio?: string;
    requesters?: string;
    timeline?: string;
    money?: string;
  };
  highlights: WrappedHighlight[];
  // LLM-picked funniest community usernames, each with a one-liner comment.
  funniestNames: { name: string; comment: string }[];
  superlative: { title: string; text: string };
}

export interface WrappedPayload {
  edition: string;
  editionLabel: string;
  // Absent on payloads generated before language support — those are pt-BR.
  language?: WrappedLanguage;
  channel: { login: string; displayName: string; avatarUrl: string | null; bannerUrl?: string | null };
  // Twitch media captured at generation time, used as slide texture.
  media?: { vodThumbs: string[] };
  // Twitch avatars for featured community members (top requesters, donors,
  // funniest names), keyed by lowercase login. Best-effort: only donor names
  // that are valid Twitch logins get resolved.
  userAvatars?: Record<string, string>;
  generatedAt: string;
  stats: WrappedStats;
  narrative: WrappedNarrative;
  private?: WrappedPrivate;
}

export interface WrappedEdition {
  id: string;
  label: string;
  start: string; // inclusive ISO timestamp
  end: string;   // exclusive ISO timestamp
}

// Edition 1 covers everything up to the end of July 2026 (all history — rooms
// existed well before the feature). Later editions go semiannual.
export const WRAPPED_EDITIONS: WrappedEdition[] = [
  { id: '2026.1', label: 'Retrospectiva 2026.1', start: '2000-01-01T00:00:00Z', end: '2026-08-01T00:00:00Z' },
];

export const CURRENT_WRAPPED_EDITION = WRAPPED_EDITIONS[WRAPPED_EDITIONS.length - 1];

export function getWrappedEdition(id: string): WrappedEdition | undefined {
  return WRAPPED_EDITIONS.find((e) => e.id === id);
}

export function wrappedEditionLabel(edition: WrappedEdition, language: WrappedLanguage): string {
  return language === 'en' ? edition.label.replace(/^Retrospectiva\b/, 'Wrapped') : edition.label;
}

// Minimum identified requests for a wrapped to be worth generating.
export const WRAPPED_MIN_REQUESTS = 10;
