name = "dbd-tracker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

[observability]
[observability.logs]
enabled = true
invocation_logs = false

[vars]
FRONTEND_URL = "http://localhost:5173"
PARTY_HOST = "localhost:1999"

[[d1_databases]]
binding = "DB"
database_name = "fila-dbd"
database_id = "local"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "local"

[env.production]
vars = { FRONTEND_URL = "https://filadbd.pages.dev", PARTY_HOST = "dbd-tracker-party.macecchi.partykit.dev" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "fila-dbd"
database_id = "0b7fe20d-bc00-4399-b58d-2923aaab201c"
migrations_dir = "migrations"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "d969f51392e9471790da97ea9c053506"
